(function () {
  window.ACoordState = {
    currentStructure: null,
    currentSelectedAtom: null,
    currentSelectedBondKey: null,
    selectedBondKeys: [],
    selectedAtomIds: [],
    isDragging: false,
    dragAtomId: null,
    adsorptionReferenceId: null,
    adsorptionAdsorbateIds: [],
    manualScale: 1,
    autoScaleEnabled: false,
    atomSizeScale: 1,
    bondThicknessScale: 1,
    viewZoom: 1,
    projectionMode: 'orthographic',
    scaleAtomsWithLattice: false,
    supercell: [1, 1, 1],
    unitCellEditing: false,
    renderAtomOffsets: {},
    shouldFitCamera: true,
    groupMoveActive: false,
    trajectoryFrameIndex: 0,
    trajectoryFrameCount: 1,
    trajectoryPlaying: false,
    trajectoryPlaybackFps: 8,
    lastDragWorld: null,
    dragPlaneNormal: null,
    rotationAxis: 'z',
    rotationInProgress: false,
    // Display settings
    showAxes: true,
    backgroundColor: '#0d1015',
    unitCellColor: '#FF6600',
    unitCellThickness: 1,
    unitCellLineStyle: 'solid',
    atomSizeUseDefaultSettings: true,
    atomSizeGlobal: 0.3,
    atomSizeByElement: {},
    atomSizeByAtom: {},
    atomSizeElementExpanded: false,
    shininess: 50,
    // Lighting settings
    lightingEnabled: true,
    ambientIntensity: 0.5,
    ambientColor: '#ffffff',
    keyLight: { intensity: 0.7, x: 0, y: 0, z: 10, color: '#CCCCCC' },
    fillLight: { intensity: 0, x: -10, y: -5, z: 5, color: '#ffffff' },
    rimLight: { intensity: 0, x: 0, y: 5, z: -10, color: '#ffffff' },
  };
})();
