import { Structure } from '../../models/structure.js';
import { Atom } from '../../models/atom.js';
import { UnitCell } from '../../models/unitCell.js';
import { parseElement, getDefaultAtomRadius } from '../../utils/elementData.js';
import { BRIGHT_SCHEME } from '../../config/presets/color-schemes/index.js';
import { StructureParser } from './structureParser.js';
import { BOHR_TO_ANGSTROM } from '../../utils/constants.js';

interface BlockData {
  lines: string[];
  unit?: string;
}

interface ConstraintEntry {
  species: string;
  instanceIndex: number;
  vector: [number, number, number];
}

interface ParsedCellData {
  blocks: Map<string, BlockData>;
  keywords: Map<string, string>;
}

export class CellParser extends StructureParser {
  private static readonly UNIT_FACTORS: Record<string, number> = {
    'ang': 1.0,
    'bohr': BOHR_TO_ANGSTROM,
    'a0': BOHR_TO_ANGSTROM,
    'm': 1e10,
    'cm': 1e8,
    'nm': 10.0,
    'pm': 0.01,
  };

  parse(content: string): Structure {
    if (!content.trim()) {
      throw new Error('CellParser: empty input');
    }

    const { blocks, keywords } = this.parseFreeForm(content);
    const structure = new Structure('', true);
    structure.isCrystal = true;

    this.parseLattice(blocks, structure);
    this.parsePositions(blocks, structure);

    if (structure.atoms.length === 0) {
      throw new Error('CellParser: no atom positions found in file');
    }

    const speciesMassBlock = blocks.get('species_mass');
    if (speciesMassBlock) {
      this.parseSpeciesMass(speciesMassBlock, structure);
    }

    const ionicConstraintsBlock = blocks.get('ionic_constraints');
    if (ionicConstraintsBlock) {
      this.parseIonicConstraints(ionicConstraintsBlock, structure);
    }

    this.saveCellMetadata(blocks, keywords, structure);
    this.applyAtomColorsAndRadii(structure);
    this.initializeSpinMetadata(structure);

    return structure;
  }

  serialize(structure: Structure): string {
    const lines: string[] = [];
    lines.push('# Generated by ACoord');
    lines.push('');

    const cellKeywords = structure.metadata.get('cellKeywords') as Record<string, string> | undefined;
    const cellBlocks = structure.metadata.get('cellBlocks') as Record<string, string> | undefined;

    if (cellKeywords) {
      for (const [key, value] of Object.entries(cellKeywords)) {
        lines.push(`${key.toUpperCase()}: ${value}`);
      }
      if (Object.keys(cellKeywords).length > 0) {
        lines.push('');
      }
    }

    if (structure.unitCell) {
      lines.push('%BLOCK LATTICE_CART ang');
      const vectors = structure.unitCell.getLatticeVectors();
      for (const vec of vectors) {
        lines.push(`  ${vec[0].toFixed(10)}  ${vec[1].toFixed(10)}  ${vec[2].toFixed(10)}`);
      }
      lines.push('%ENDBLOCK LATTICE_CART');
      lines.push('');
    }

    lines.push('%BLOCK POSITIONS_FRAC');
    const spinArray = structure.metadata.get('spin') as number[] | undefined;
    
    for (let i = 0; i < structure.atoms.length; i++) {
      const atom = structure.atoms[i];
      let fx = atom.x;
      let fy = atom.y;
      let fz = atom.z;
      
      if (structure.unitCell) {
        const frac = structure.unitCell.cartesianToFractional(atom.x, atom.y, atom.z);
        fx = frac[0];
        fy = frac[1];
        fz = frac[2];
      }

      let line = `${atom.element}  ${fx.toFixed(10)}  ${fy.toFixed(10)}  ${fz.toFixed(10)}`;
      
      if (spinArray && i < spinArray.length && spinArray[i] !== 0) {
        line += `  SPIN=${spinArray[i]}`;
      }
      
      if (atom.label) {
        line += `  LABEL=${atom.label}`;
      }
      
      lines.push(line);
    }
    lines.push('%ENDBLOCK POSITIONS_FRAC');
    lines.push('');

    const speciesMass = structure.metadata.get('speciesMass') as Record<string, number> | undefined;
    if (speciesMass && Object.keys(speciesMass).length > 0) {
      lines.push('%BLOCK SPECIES_MASS');
      for (const [species, mass] of Object.entries(speciesMass)) {
        lines.push(`${species}  ${mass}`);
      }
      lines.push('%ENDBLOCK SPECIES_MASS');
      lines.push('');
    }

    const constraints = this.serializeIonicConstraints(structure);
    if (constraints.length > 0) {
      lines.push('%BLOCK IONIC_CONSTRAINTS');
      for (const constraint of constraints) {
        lines.push(constraint);
      }
      lines.push('%ENDBLOCK IONIC_CONSTRAINTS');
      lines.push('');
    }

    if (cellBlocks) {
      for (const [blockName, blockContent] of Object.entries(cellBlocks)) {
        lines.push(`%BLOCK ${blockName.toUpperCase()}`);
        lines.push(blockContent);
        lines.push(`%ENDBLOCK ${blockName.toUpperCase()}`);
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  private parseFreeForm(content: string): ParsedCellData {
    const blocks = new Map<string, BlockData>();
    const keywords = new Map<string, string>();
    const lines = content.split(/\r?\n/);
    
    let currentBlock: string | null = null;
    let currentLines: string[] = [];
    let currentUnit: string | undefined;

    for (let i = 0; i < lines.length; i++) {
      const raw = lines[i];
      const stripped = this.stripComment(raw).trim();
      
      if (!stripped) {
        continue;
      }

      const lower = stripped.toLowerCase();

      if (lower.startsWith('%block')) {
        const tokens = stripped.split(/\s+/);
        if (tokens.length < 2) {
          throw new Error(`CellParser: line ${i + 1}: invalid %BLOCK statement`);
        }
        currentBlock = tokens[1].toLowerCase();
        currentLines = [];
        currentUnit = undefined;

        if (tokens.length >= 3) {
          currentUnit = tokens[2].toLowerCase();
        }
        continue;
      }

      if (lower.startsWith('%endblock')) {
        const tokens = stripped.split(/\s+/);
        if (tokens.length < 2) {
          throw new Error(`CellParser: line ${i + 1}: invalid %ENDBLOCK statement`);
        }
        const endBlock = tokens[1].toLowerCase();
        
        if (currentBlock && endBlock === currentBlock) {
          blocks.set(currentBlock, { lines: currentLines, unit: currentUnit });
        }
        currentBlock = null;
        currentLines = [];
        currentUnit = undefined;
        continue;
      }

      if (currentBlock) {
        currentLines.push(stripped);
        if (currentLines.length === 1 && !currentUnit) {
          const firstTokens = stripped.split(/\s+/);
          if (firstTokens.length > 0) {
            const potentialUnit = firstTokens[0].toLowerCase();
            if (CellParser.UNIT_FACTORS[potentialUnit]) {
              const rest = firstTokens.slice(1);
              if (rest.length === 0 || !this.looksLikeCoordinateLine(stripped)) {
                currentUnit = potentialUnit;
                currentLines = [];
              }
            }
          }
        }
      } else {
        const colonIndex = stripped.indexOf(':');
        const equalIndex = stripped.indexOf('=');
        let key: string;
        let value: string;
        
        if (colonIndex > 0 && (equalIndex < 0 || colonIndex < equalIndex)) {
          key = stripped.substring(0, colonIndex).trim().toLowerCase();
          value = stripped.substring(colonIndex + 1).trim();
        } else if (equalIndex > 0) {
          key = stripped.substring(0, equalIndex).trim().toLowerCase();
          value = stripped.substring(equalIndex + 1).trim();
        } else {
          const tokens = stripped.split(/\s+/);
          if (tokens.length >= 1) {
            key = tokens[0].toLowerCase();
            value = tokens.length > 1 ? tokens.slice(1).join(' ') : '';
            keywords.set(key, value);
          }
          continue;
        }
        
        keywords.set(key, value);
      }
    }

    return { blocks, keywords };
  }

  private looksLikeCoordinateLine(line: string): boolean {
    const tokens = line.split(/\s+/);
    if (tokens.length < 3) {return false;}
    const num = parseFloat(tokens[0]);
    return !isNaN(num);
  }

  private parseLattice(blocks: Map<string, BlockData>, structure: Structure): void {
    const hasCart = blocks.has('lattice_cart');
    const hasAbc = blocks.has('lattice_abc');

    if (!hasCart && !hasAbc) {
      throw new Error('CellParser: missing LATTICE_CART or LATTICE_ABC block');
    }

    const latticeCartBlock = blocks.get('lattice_cart');
    const latticeAbcBlock = blocks.get('lattice_abc');
    if (hasCart && latticeCartBlock) {
      this.parseLatticeCart(latticeCartBlock, structure);
    } else if (latticeAbcBlock) {
      this.parseLatticeAbc(latticeAbcBlock, structure);
    }
  }

  private parseLatticeCart(block: BlockData, structure: Structure): void {
    let lines = block.lines;
    let unitFactor = 1.0;

    if (block.unit) {
      unitFactor = this.getUnitFactor(block.unit);
    } else if (lines.length > 0) {
      const firstTokens = lines[0].split(/\s+/);
      if (firstTokens.length > 0 && CellParser.UNIT_FACTORS[firstTokens[0].toLowerCase()]) {
        unitFactor = this.getUnitFactor(firstTokens[0].toLowerCase());
        lines = lines.slice(1);
      }
    }

    if (lines.length < 3) {
      throw new Error('CellParser: LATTICE_CART requires at least 3 lines');
    }

    const vectors: number[][] = [];
    for (let i = 0; i < 3 && i < lines.length; i++) {
      const tokens = lines[i].split(/\s+/);
      if (tokens.length < 3) {
        throw new Error(`CellParser: invalid lattice vector at line ${i + 1}`);
      }
      const vec = tokens.slice(0, 3).map(v => parseFloat(v) * unitFactor);
      if (vec.some(v => !Number.isFinite(v))) {
        throw new Error(`CellParser: invalid lattice vector values at line ${i + 1}`);
      }
      vectors.push(vec);
    }

    structure.unitCell = UnitCell.fromVectors(vectors);
  }

  private parseLatticeAbc(block: BlockData, structure: Structure): void {
    let lines = block.lines;
    let unitFactor = 1.0;

    if (block.unit) {
      unitFactor = this.getUnitFactor(block.unit);
    } else if (lines.length > 0) {
      const firstTokens = lines[0].split(/\s+/);
      if (firstTokens.length > 0 && CellParser.UNIT_FACTORS[firstTokens[0].toLowerCase()]) {
        unitFactor = this.getUnitFactor(firstTokens[0].toLowerCase());
        lines = lines.slice(1);
      }
    }

    if (lines.length < 2) {
      throw new Error('CellParser: LATTICE_ABC requires at least 2 lines');
    }

    const abcTokens = lines[0].split(/\s+/);
    const angleTokens = lines[1].split(/\s+/);

    if (abcTokens.length < 3 || angleTokens.length < 3) {
      throw new Error('CellParser: invalid LATTICE_ABC format');
    }

    const a = parseFloat(abcTokens[0]) * unitFactor;
    const b = parseFloat(abcTokens[1]) * unitFactor;
    const c = parseFloat(abcTokens[2]) * unitFactor;
    const alpha = parseFloat(angleTokens[0]);
    const beta = parseFloat(angleTokens[1]);
    const gamma = parseFloat(angleTokens[2]);

    if (!Number.isFinite(a) || !Number.isFinite(b) || !Number.isFinite(c)) {
      throw new Error('CellParser: invalid lattice parameters');
    }

    structure.unitCell = new UnitCell(a, b, c, alpha || 90, beta || 90, gamma || 90);
  }

  private parsePositions(blocks: Map<string, BlockData>, structure: Structure): void {
    const hasAbs = blocks.has('positions_abs');
    const hasFrac = blocks.has('positions_frac');

    if (!hasAbs && !hasFrac) {
      throw new Error('CellParser: missing POSITIONS_ABS or POSITIONS_FRAC block');
    }

    const positionsAbsBlock = blocks.get('positions_abs');
    const positionsFracBlock = blocks.get('positions_frac');
    if (hasAbs && positionsAbsBlock) {
      this.parsePositionsAbs(positionsAbsBlock, structure);
    } else if (positionsFracBlock) {
      this.parsePositionsFrac(positionsFracBlock, structure);
    }
  }

  private parsePositionsAbs(block: BlockData, structure: Structure): void {
    let lines = block.lines;
    let unitFactor = 1.0;

    if (block.unit) {
      unitFactor = this.getUnitFactor(block.unit);
    } else if (lines.length > 0) {
      const firstTokens = lines[0].split(/\s+/);
      if (firstTokens.length > 0 && CellParser.UNIT_FACTORS[firstTokens[0].toLowerCase()]) {
        unitFactor = this.getUnitFactor(firstTokens[0].toLowerCase());
        lines = lines.slice(1);
      }
    }

    for (const line of lines) {
      this.parsePositionLine(line, structure, unitFactor, false);
    }
  }

  private parsePositionsFrac(block: BlockData, structure: Structure): void {
    const lines = block.lines;

    for (const line of lines) {
      this.parsePositionLine(line, structure, 1.0, true);
    }
  }

  private parsePositionLine(
    line: string,
    structure: Structure,
    unitFactor: number,
    isFractional: boolean
  ): void {
    const tokens = line.split(/\s+/);
    if (tokens.length < 4) {
      return;
    }

    const species = tokens[0];
    const baseElement = this.getBaseElement(species);
    const parsedElement = parseElement(baseElement);
    
    if (!parsedElement) {
      return;
    }

    let x = parseFloat(tokens[1]);
    let y = parseFloat(tokens[2]);
    let z = parseFloat(tokens[3]);

    if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) {
      return;
    }

    if (!isFractional) {
      x *= unitFactor;
      y *= unitFactor;
      z *= unitFactor;
    }

    if (isFractional && structure.unitCell) {
      const cart = structure.unitCell.fractionalToCartesian(x, y, z);
      x = cart[0];
      y = cart[1];
      z = cart[2];
    }

    const atom = new Atom(species, x, y, z, undefined, {
      color: BRIGHT_SCHEME.colors[baseElement] || '#C0C0C0',
      radius: getDefaultAtomRadius(baseElement),
    });

    const additionalInfo = this.parseAdditionalInfo(tokens.slice(4));
    if (additionalInfo.spin !== undefined) {
      const spinArray = (structure.metadata.get('spin') as number[]) || [];
      while (spinArray.length < structure.atoms.length) {
        spinArray.push(0);
      }
      spinArray.push(additionalInfo.spin);
      structure.metadata.set('spin', spinArray);
    }

    if (additionalInfo.label) {
      atom.label = additionalInfo.label;
    }

    structure.addAtom(atom);
  }

  private parseAdditionalInfo(tokens: string[]): { spin?: number; label?: string } {
    const result: { spin?: number; label?: string } = {};
    const joined = tokens.join(' ');

    const spinMatch = joined.match(/SPIN\s*[=:\s]\s*([+-]?\d*\.?\d+)/i);
    if (spinMatch) {
      result.spin = parseFloat(spinMatch[1]);
    }

    const labelMatch = joined.match(/LABEL\s*[=:\s]\s*(\S+)/i);
    if (labelMatch) {
      result.label = labelMatch[1].replace(/^['"]|['"]$/g, '');
    }

    return result;
  }

  private parseSpeciesMass(block: BlockData, structure: Structure): void {
    let lines = block.lines;

    const speciesMass: Record<string, number> = {};

    for (const line of lines) {
      const tokens = line.split(/\s+/);
      if (tokens.length < 2) {
        continue;
      }

      const species = tokens[0];
      const mass = parseFloat(tokens[1]);

      if (Number.isFinite(mass)) {
        speciesMass[species] = mass;
      }
    }

    if (Object.keys(speciesMass).length > 0) {
      structure.metadata.set('speciesMass', speciesMass);
    }
  }

  private parseIonicConstraints(block: BlockData, structure: Structure): void {
    const constraints: ConstraintEntry[] = [];

    for (const line of block.lines) {
      const tokens = line.split(/\s+/);
      if (tokens.length < 6) {
        continue;
      }

      const instanceIndex = parseInt(tokens[2]);
      const vx = parseFloat(tokens[3]);
      const vy = parseFloat(tokens[4]);
      const vz = parseFloat(tokens[5]);

      if (!Number.isFinite(instanceIndex) ||
          !Number.isFinite(vx) ||
          !Number.isFinite(vy) ||
          !Number.isFinite(vz)) {
        continue;
      }

      constraints.push({
        species: tokens[1],
        instanceIndex,
        vector: [vx, vy, vz],
      });
    }

    this.applyConstraintsToAtoms(constraints, structure);
  }

  private applyConstraintsToAtoms(constraints: ConstraintEntry[], structure: Structure): void {
    const atomGroups = this.buildAtomGroups(structure);
    const constraintCount = new Map<string, number>();

    for (const constraint of constraints) {
      const atoms = atomGroups.get(constraint.species);
      if (!atoms || constraint.instanceIndex > atoms.length || constraint.instanceIndex < 1) {
        continue;
      }

      const atom = atoms[constraint.instanceIndex - 1];
      this.applyConstraintToAtom(atom, constraint.vector);

      const key = atom.id;
      constraintCount.set(key, (constraintCount.get(key) || 0) + 1);
    }

    for (const atom of structure.atoms) {
      if (atom.selectiveDynamics) {
        atom.fixed = atom.selectiveDynamics.every(d => !d);
      }
    }
  }

  private applyConstraintToAtom(atom: Atom, vector: [number, number, number]): void {
    if (!atom.selectiveDynamics) {
      atom.selectiveDynamics = [true, true, true];
    }

    const threshold = 0.5;

    if (Math.abs(vector[0]) > threshold) {
      atom.selectiveDynamics[0] = false;
    }
    if (Math.abs(vector[1]) > threshold) {
      atom.selectiveDynamics[1] = false;
    }
    if (Math.abs(vector[2]) > threshold) {
      atom.selectiveDynamics[2] = false;
    }
  }

  private buildAtomGroups(structure: Structure): Map<string, Atom[]> {
    const groups = new Map<string, Atom[]>();

    for (const atom of structure.atoms) {
      let group = groups.get(atom.element);
      if (!group) {
        group = [];
        groups.set(atom.element, group);
      }
      group.push(atom);
    }

    return groups;
  }

  private serializeIonicConstraints(structure: Structure): string[] {
    const constraints: string[] = [];
    const atomGroups = this.buildAtomGroups(structure);
    let constraintId = 1;

    for (const [species, atoms] of atomGroups) {
      atoms.forEach((atom, idx) => {
        const sd = atom.selectiveDynamics ?? [true, true, true];
        const [sx, sy, sz] = sd;

        if (!sx) {
          constraints.push(`${constraintId}  ${species}  ${idx + 1}  1 0 0`);
          constraintId++;
        }
        if (!sy) {
          constraints.push(`${constraintId}  ${species}  ${idx + 1}  0 1 0`);
          constraintId++;
        }
        if (!sz) {
          constraints.push(`${constraintId}  ${species}  ${idx + 1}  0 0 1`);
          constraintId++;
        }
      });
    }

    return constraints;
  }

  private initializeSpinMetadata(structure: Structure): void {
    if (!structure.metadata.has('spin')) {
      const spinArray = new Array(structure.atoms.length).fill(0);
      structure.metadata.set('spin', spinArray);
    }
  }

  private applyAtomColorsAndRadii(structure: Structure): void {
    for (const atom of structure.atoms) {
      const base = this.getBaseElement(atom.element);
      atom.color = BRIGHT_SCHEME.colors[base] || '#C0C0C0';
      atom.radius = getDefaultAtomRadius(base);
    }
  }

  private getBaseElement(species: string): string {
    return species.split(':')[0];
  }

  private getUnitFactor(unit: string): number {
    const lower = unit.toLowerCase();
    const factor = CellParser.UNIT_FACTORS[lower];
    if (factor === undefined) {
      return 1.0;
    }
    return factor;
  }

  private stripComment(line: string): string {
    const commentChars = ['#', '!', ';'];
    let result = line;

    for (const char of commentChars) {
      const idx = result.indexOf(char);
      if (idx >= 0) {
        result = result.slice(0, idx);
      }
    }

    return result;
  }

  private saveCellMetadata(
    blocks: Map<string, BlockData>,
    keywords: Map<string, string>,
    structure: Structure
  ): void {
    const cellKeywords: Record<string, string> = {};
    const cellBlocks: Record<string, string> = {};

    for (const [key, value] of keywords) {
      cellKeywords[key] = value;
    }

    const parsedBlocks = new Set([
      'lattice_cart',
      'lattice_abc',
      'positions_abs',
      'positions_frac',
      'species_mass',
      'ionic_constraints',
    ]);

    for (const [blockName, blockData] of blocks) {
      if (!parsedBlocks.has(blockName)) {
        cellBlocks[blockName] = blockData.lines.join('\n');
      }
    }

    if (Object.keys(cellKeywords).length > 0 || Object.keys(cellBlocks).length > 0) {
      structure.metadata.set('cellKeywords', cellKeywords);
      structure.metadata.set('cellBlocks', cellBlocks);
    }
  }
}
